Metrics/MethodLength:
  Enabled: False

Metrics/BlockLength:
  Enabled: False

Metrics/AbcSize:
  Enabled: False

Gemspec/DevelopmentDependencies:
  Enabled: False

Gemspec/DeprecatedAttributeAssignment:
  Enabled: False

AllCops:
  NewCops: enable